### ISSUE TITLE
Ensure consistent requirements between TI lifecycle docs

### ISSUE THREAD

**Issue by marcelamelara** [ossf/tac#268]
The [TI Gives + Gets](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md) currently diverge from the requirements for TI lifecycle stages ([WG](https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md), [Project](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md) and [SIG](https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md)). 

There are two areas where we need to evaluate the docs for consistency and completeness:
* Role of the TAC sponsor (#263)
* Requirements for each type of TI at each stage 

This issue is meant to track the tasks needed to resolve any remaining inconsistencies and missing requirements:

- [x] Role of TAC sponsor (#262)
- [x] Requirements for WGs
- [ ] Requirements for [SIFs](https://github.com/ossf/tac/issues/85)
- [x] Requirements for Projects
- [x] Requirements for SIGs
- [x] Ensure alignment between TI Gives+Gets, lifecycle docs, templates (#295, #296, #297)

Per the [2/20/2024 TAC meeting discussion](https://docs.google.com/document/d/1-zrtagRnPd75TDT1zRxrtxE9SpMIBJdPmaolaw4woQA/edit?pli=1#heading=h.bn32biavysar), there's a need to revisit and document specific repo-structure requirements for TIs (e.g., charter updates, other .md files, etc).

There's also a desire to lower the barrier to entry for non-WG sandbox stage TIs and make TAC approval optional.
For instance, the TI G+Gs currently [require sandbox TIs](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#givesrequirements) to adhere to the SSDGP and the Open Source Consumption Manifesto. These requirements only make sense for project TIs, and it's not clear if these are too steep a requirement for sandbox-level projects.

**Comment by lehors** [comment]
I think it's a healthy thing to do to review what we have and make sure the differences we have are intentional and not just merely accidental. However, we shouldn't assume that we ought to have alignment across all TIs. Some differences are intentional and ought to be kept. We do not want the TAC to be the sole point of control. Delegation of that control is key to scalability.

**Comment by marcelamelara** [comment]
Totally agree. I think part of the current issue is that the TI G+Gs don't always make the distinction between different types of TIs and their specific requirements. So we have this muddled set of requirements at the moment (in that doc). My ideal outcome for this issue would be to have the lifecycle docs be the clear authoritative source for requirements, and deduplicate this information from the Gives + Gets to avoid confusion :)

**Comment by marcelamelara** [comment]
Moving this discussion from https://github.com/ossf/tac/pull/262/files#r1491166612 here.

My summary:
* Should SIGs and Projects _require_ TAC approval for lifecycle transitions?
* How do we reconcile the need for opening a PR in this repo to submit a project's or SIG's sandbox application (which effectively amounts to a TAC approval) with the desire to make the TAC approval optional for projects and SIGs? Is this really about online vs offline TAC votes? 

@steiza please let me know if I missed anything!

**Comment by lehors** [comment]
> My summary:
> 
>     * Should SIGs and Projects _require_ TAC approval for lifecycle transitions?

SIGs should not for sure.

>     * How do we reconcile the need for opening a PR in this repo to submit a project's or SIG's sandbox application (which effectively amounts to a TAC approval) with the desire to make the TAC approval optional for projects and SIGs? Is this really about online vs offline TAC votes?

For SIGs we clearly state that:

> SIGs can be created and managed without formal approval from the TAC.
[...]
> Because no formal approval by the TAC is required the PR can be merged by any TAC or staff member.

https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md#sig-creation-or-change-of-lifecycle-stage

**Comment by marcelamelara** [comment]
Yes! I went back and edited my questions afterwards to adjust for the fact that this is already clearly laid out for SIGs.

**Comment by lehors** [comment]
Something could probably be done to make that kind of information easier to find but this might take some skilled person.

**Comment by SecurityCRob** [comment]
> > My summary:
> > ```
> > * Should SIGs and Projects _require_ TAC approval for lifecycle transitions?
> > ```
> 
> SIGs should not for sure.
> 
> > ```
> > * How do we reconcile the need for opening a PR in this repo to submit a project's or SIG's sandbox application (which effectively amounts to a TAC approval) with the desire to make the TAC approval optional for projects and SIGs? Is this really about online vs offline TAC votes?
> > ```
> 
> For SIGs we clearly state that:
> 
> > SIGs can be created and managed without formal approval from the TAC.
> > [...]
> > Because no formal approval by the TAC is required the PR can be merged by any TAC or staff member.
> 
> https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md#sig-creation-or-change-of-lifecycle-stage

Agreed

**Comment by SecurityCRob** [comment]
> Something could probably be done to make that kind of information easier to find but this might take some skilled person.

Also agreed.  We need to make this stuff better accessible.  updating the landing page will help, but more ideas and suggestions are welcome.

**Comment by SecurityCRob** [comment]
SANDBOX
https://github.com/ossf/tac/pull/274
https://github.com/ossf/tac/pull/282
https://github.com/ossf/tac/pull/275
INCUBATING
https://github.com/ossf/tac/pull/276
https://github.com/ossf/tac/pull/277
https://github.com/ossf/tac/pull/278
GRADUATED
https://github.com/ossf/tac/pull/279
https://github.com/ossf/tac/pull/280
https://github.com/ossf/tac/pull/281

**Comment by SecurityCRob** [comment]
Do we think that the requirements are now aligned between the project, WG, ans SIG documents?  What needs adjusted for the Gives and Gets and who is interested in fleshing out "SIF" (if we still desire to have that category?)?

**Comment by marcelamelara** [comment]
Thanks for ping on this. I think once #295 and #296 are merged, we'll be there.

**Comment by marcelamelara** [comment]
I think we can close this now. One piece we have left to resolve is the discussion from #85, we can focus the conversation in that issue.
